### ISSUE TITLE
Add bases to board string

### ISSUE THREAD

**Issue by Mark-Boon** [Mark-Boon/SoftwareSystems_Ringzz_game#13]
- Each place on one pin should be filled, for example when done with color red: 
R R
R R

**Comment by CraftingLevi** [comment]
This issue has been resolved. However, there is still one little quirk: 
- The current implementation replaces the tiles on the board with:
1R 1R
1R 1R
for player 1 owning color "r"
- With this implementation, I added the function "getTile(int index)" to the board, returning a String representation of the Tile with a certain index. for an empty tile, this would be "0 0 0 0 0", for the tile I show above this would be 0 1R 1R 1R 1R. When trying to find a winner, it will most likely be more efficient to also mark the first marker of the field in case of a base: in this way, no calculations need to happen with the other values in this string (faster identification a tile is containing a base)
